# version: '3.8'

# services:
#   postgres:
#     image: postgres:13
#     environment:
#       POSTGRES_DB: insurance_db
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#     ports:
#       - "5432:5432"
#     volumes:
#       - postgres_data:/var/lib/postgresql/data
#     # No init.sql - using existing table
#     healthcheck:
#       test: ["CMD-SHELL", "pg_isready -U postgres"]
#       interval: 10s
#       timeout: 5s
#       retries: 5

# volumes:
#   postgres_data: