# params.yaml
data_ingestion:
  train_test_split_ratio: 0.2
  table_name: "insurance"
  schema_name: "public"

data_validation:
  validation_threshold: 0.8
  drift_threshold: 0.1

data_transformation:
  numerical_scaler: "StandardScaler"
  categorical_encoder: "OneHotEncoder"

model_trainer:
  expected_accuracy: 0.6
  model_selection_method: "grid_search"