model_hyperparameters:
  random_forest:
    n_estimators: [100, 200, 300]
    max_depth: [10, 20, None]
    min_samples_split: [2, 5, 10]
    min_samples_leaf: [1, 2, 4]
    random_state: 42

  xgboost:
    n_estimators: [100, 200, 300]
    max_depth: [3, 6, 9]
    learning_rate: [0.01, 0.1, 0.3]
    subsample: [0.8, 0.9, 1.0]
    random_state: 42

  gradient_boosting:
    n_estimators: [100, 200]
    learning_rate: [0.05, 0.1, 0.2]
    max_depth: [3, 4, 5]
    subsample: [0.8, 0.9]
    random_state: 42

feature_engineering:
  outlier_handling:
    method: "winsorize"
    limits: [0.05, 0.05]
  
  feature_creation:
    - risk_score: "(age / 10) * (bmi / 25) * smoker_map"
    - bmi_categories: "pd.cut(bmi, bins=[0, 18.5, 25, 30, 35, 40, 100])"
    - age_categories: "pd.cut(age, bins=[18, 30, 40, 50, 60, 100])"

preprocessing:
  numerical:
    scaler: "StandardScaler"
    transformer: "PowerTransformer"
  
  categorical:
    encoder: "OneHotEncoder"
    handle_unknown: "ignore"
    drop_first: true