grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 5
    verbose: 3
    scoring: neg_mean_squared_error

model_selection:
  module_0:
    class: RandomForestRegressor
    module: sklearn.ensemble
    params:
      n_estimators: 100
      random_state: 42
    search_param_grid:
      n_estimators: [100, 200, 300]
      max_depth: [10, 20, None]
      min_samples_split: [2, 5]
      min_samples_leaf: [1, 2]

  module_1:
    class: XGBRegressor
    module: xgboost
    params:
      random_state: 42
    search_param_grid:
      n_estimators: [100, 200, 300]
      max_depth: [3, 6, 9]
      learning_rate: [0.01, 0.1, 0.3]

  module_2:
    class: GradientBoostingRegressor
    module: sklearn.ensemble
    params:
      random_state: 42
    search_param_grid:
      n_estimators: [100, 200]
      learning_rate: [0.05, 0.1, 0.2]
      max_depth: [3, 4, 5]