# config/schema.yaml
columns:
  - age: int
  - sex: category
  - bmi: float
  - children: int
  - smoker: category
  - region: category
  - charges: float

numerical_columns:
  - age
  - bmi
  - children
  - charges

categorical_columns:
  - sex
  - smoker
  - region

drop_columns: []

# for data transformation
num_features:
  - age
  - bmi
  - children

or_columns:
  - sex
  - smoker

oh_columns:
  - region

transform_columns:
  - bmi

target_column: charges